### ISSUE TITLE
Reentry map empty when installing from pypi.

### ISSUE THREAD

**Issue by greschd** [DropD/reentry#43] opened 2019-01-23 09:25 UTC
When installing a package from pypi as opposed to the github link, the ``reentry map`` does not show the installed packages.

Steps to reproduce (using Python 3.6, pip 18.1):

```
pip install aiida-core==1.0.0a4
reentry map
```

this however works:

```
pip install git+https://github.com/aiidateam/aiida_core@v1.0.0a4#egg=aiida_core
reentry map
```

**Comment by ltalirz** [comment] 2019-01-23 09:38
Unable to reproduce this in a fresh conda environment with:
 * conda 4.5.11
 * python 3.6.8
 * pip 18.1
Just did `pip install aiida-core==1.0.0a4` and `reentry map` was already populated.

**Comment by ltalirz** [comment] 2019-01-23 09:57
>  I got the issue both on my local machine and on Travis

Would you mind providing a link to the travis log?

Also, did the issue appear recently or did you just switch from github to pypi?

**Comment by greschd** [comment] 2019-01-23 10:03
Sure, it's https://travis-ci.org/greschd/aiida-strain/jobs/483302776

The issue comes up here not with aiida-core but with my plugin (for core I still used the git link). I've only recently switched to pypi install, so not sure if it's a recent issue.

Am 23.01.2019 10:57 schrieb Leopold Talirz <notifications@github.com>:

I got the issue both on my local machine and on Travis

Would you mind providing a link to the travis log?

Also, did the issue appear recently or did you just switch from github to pypi?

**Comment by ltalirz** [comment] 2019-01-23 10:10
Sorry for being a bit slow here but the travis log seems to only show pip installs from git repositories (+ the local one). Which is the install from pypi that doesn't behave as expected?

**Comment by greschd** [comment] 2019-01-23 15:01
It's ``aiida-symmetry-representation``, one of my packages which is a dependency of the code I'm testing here. The install is here: https://travis-ci.org/greschd/aiida-strain/jobs/483302776#L845

**Comment by greschd** [comment] 2019-01-23 15:02
I don't explicitly show the ``reentry map`` on Travis, but adding ``reentry scan`` after install (see the following build) fixes the issue.

**Comment by greschd** [comment] 2019-01-23 15:04
Just for completeness' sake, here's the pip freeze I get on an empty virtualenv for ``aiida-core==1.0.0a4``, which produces the empty reentry map:

```
aiida-core==1.0.0a4
aldjemy==0.8.0
alembic==0.9.9
anyjson==0.3.3
asn1crypto==0.24.0
bcrypt==3.1.6
cffi==1.11.5
circus==0.14.0
click==6.7
click-completion==0.3.1
click-plugins==1.0.3
click-spinner==0.1.7
cryptography==2.5
decorator==4.3.0
Django==1.8.19
django-extensions==1.5.0
ecdsa==0.13
ete3==3.1.1
frozendict==1.2
future==0.17.1
iowait==0.2
ipython==5.8.0
ipython-genutils==0.2.0
Jinja2==2.10
kiwipy==0.2.1
Mako==1.0.7
MarkupSafe==1.1.0
meld3==1.0.2
mock==2.0.0
numpy==1.14.3
paramiko==2.4.2
passlib==1.7.1
pbr==5.1.1
pexpect==4.6.0
pickleshare==0.7.5
pika==0.12.0
plumpy==0.10.6
portalocker==1.3.0
prompt-toolkit==1.0.15
psutil==5.4.5
psycopg2-binary==2.7.4
ptyprocess==0.6.0
py==1.7.0
pyasn1==0.4.5
pycparser==2.19
Pygments==2.3.1
PyNaCl==1.3.0
python-dateutil==2.7.2
python-editor==1.0.3
python-mimeparse==1.6.0
pytz==2018.4
PyYAML==3.12
pyzmq==17.1.2
reentry==1.2.1
simplegeneric==0.8.1
simplejson==3.16.0
six==1.11.0
SQLAlchemy==1.0.19
SQLAlchemy-Utils==0.33.0
tabulate==0.8.2
tornado==4.5.3
traitlets==4.3.2
tzlocal==1.5.1
ujson==1.35
uritools==2.1.0
validate-email==1.3
wcwidth==0.1.7
```

Setuptools is version 40.6.3.

**Comment by ltalirz** [comment] 2019-01-23 15:33
reproduced in python 2.7.15 virtualenv on Quantum Mobile 18.10RC2 (Ubuntu 18.04).
After `pip install aiida-core==1.0.0a4`, the reentry map is empty.

**Comment by greschd** [comment] 2019-01-23 15:40
Yay, I'm not crazy :smile:

**Comment by DropD** [comment] 2019-02-12 19:26
I don't know the reason for this, but I have been able to trace it to a change between pip 18.0 and pip 18.1, because I do get a full map with the former and an empty one with the latter.

**Comment by ltalirz** [comment] 2019-04-12 14:04
Actually, it seems to me this comes from a very basic fact: the `setup.py` is not used when installing wheels.

`setuptools` does call the [`reentry_register` entry point](https://setuptools.readthedocs.io/en/latest/setuptools.html#adding-setup-arguments) when *building* a wheel using `python setup.py bdist_wheel`. When a user then installs the wheel, however, it is just copying files.
(Note: Be careful when testing this, since the reentry cache stays around even after you uninstall `reentry`. The new `reentry clear` command comes in handy here).

While we can decide not to provide a wheel for `aiida-core`, we can't really stop plugin developers from providing wheels for their plugins.
I believe this means we anyhow need to tell people to `reentry scan`.

**Comment by greschd** [comment] 2019-05-11 08:42
Since AiiDA is mostly pure Python code the value of providing wheels w.r.t. install time doesn't seem to be worth it given this issue.

Of course we can _tell_ plugin developers not to use wheels, but probably still need to tell users to ``reentry scan`` as well.

I'm not too familiar with the wheel install process, might there be a hook to run the command in that case regardless?

**Comment by ltalirz** [comment] 2019-05-13 07:45
> I'm not too familiar with the wheel install process, might there be a hook to run the command in that case regardless?

I don't think there is one at the moment: https://github.com/pypa/packaging-problems/issues/64

I'm closing this, since I believe the original issue is addressed. The discussion whether to provide wheels for aiida-core or not can continue here: https://github.com/aiidateam/aiida_core/issues/2746

**Closed by ltalirz** 2019-05-13 07:45 UTC
Labels: bug
