### ISSUE TITLE
New plugin not automatically detected after registering

### ISSUE THREAD

**Issue by sphuber** [DropD/reentry#7] opened 2017-06-18 14:21 UTC
I encountered this issue when I first registered a new plugin for AiiDA. I pip installed it in the same virtual environment as AiiDA but neither `verdi calculation plugins` listed it afterwards, nor could I load it in `verdi shell` through the `CalculationFactory`. However, registering was successful because after running:

```
import reentry
reentry.manager.scan()
```

the plugin was properly recognized and usable. Would it be possible to trigger the managers scan somehow automatically when a new plugin is registered?

**Comment by DropD** [comment] 2017-06-19 14:45
first of all with `reentry` installed you can simply
```bash
reentry scan
```
on the commandline,

secondly, if the plugin's setup.py contains the following, the equivalent of a scan (adding only this package's entry points though) should be triggered.
```python
setup(
    ...,
    setup_requires=[
            'reentry'
    ],
    reentry_register=True,
    ...
)
```

If that does not work, it is an issue with the `reentry_register` hook.

**Comment by DropD** [comment] 2017-10-17 10:55
duplicate of #13

**Closed by DropD** 2017-10-17 10:55 UTC
